# Generated by Django 3.0.6 on 2020-07-10 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manytomany', '0002_album_track'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('std', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='manytomany.Class')),
            ],
            options={
                'ordering': ['first_name'],
                'unique_together': {('std', 'first_name', 'last_name')},
            },
        ),
    ]
